### 기안 상신
POST http://localhost:8080/api/approval/insert
Content-Type: application/json
Accept: */*
Access-Control-Allow-Origin: *

{
  "apvNo": "0003",
  "title": "타이틀",
  "writeDate": "2023-08-18",
  "apvStatus": "진행중",
  "isUrgency": "F",
  "category": "인사",
  "contents1": "내용1",
  "contents2": "내용2",
  "empNo": 999999
}

### 상신 기안 조회
GET http://localhost:8080/api/approval/write/999999
Accept: */*

