### 로그인 (헤더 - 바디 순)
POST http://localhost:8080/api/auth/login
Content-Type: application/json
Accept: */*
Access-Control-Allow-Origin: *
#Access-Control-Allow-Credentials: *

{
  "id": "user01",
  "password": "1234"
}

#### 회원가입
POST http://localhost:8080/auth/signup
Content-Type: application/json
Accept: */*

{
  "memberId": "user001",
  "memberPassword": "pass001",
  "memberName": "홍길동",
  "memberEmail": "ohgiraffers@gmail.com"
}

### 회원아이디로 조회
GET http://localhost:8080/api/v1/members/admin
Content-Type: application/json
Accept: */*
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0MDEiLCJhdXRoIjpbIlJPTEVfVVNFUiJdLCJleHAiOjE2OTE0OTU4NjF9.Z53vaFBQe4NXFyu1bbn8PZnXLmfByNNLWIp0zIIOkaWsef-ykENY76gnGyP1bvq8hRdLS8bHufiwmx8LW4mkAA

