GET http://localhost:8080/bulletin/board?categoryCode=5&currentPage=1&content=&empNo=10001
Accept: */*

###
GET http://localhost:8080/bulletin/boardTitle
Accept: */*



###
POST http://localhost:8080/bulletin/boardAdd
Content-Type: application/json
Accept: */*

{
  "nameBoard": "user001"
}

###
GET http://localhost:8080/bulletin/thread?bulletinCode=20&currentPage=1
Accept: */*