### 프로필 회원아이디로 조회
###101124564
#GET http://localhost:8080/api/mypage/profile/10005/10112
GET http://localhost:8080/api/mypage/profile/10003
Accept: */*
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIzMzMzIiwiYXV0aCI6WyJST0xFX1VTRVIiXSwiZXhwIjoxNjk0NjI0MDMzfQ.UiZcn1KVBilMA2nsIBGKsP2vTelNxJj3dkuqlbIBKVhyIfJYFZFDZxS8ERYrUAXwktx4SMVr8zuYlxv4xKDcGA
Content-Type: application/json







### 프로필파일 인서트 테스트
POST http://localhost:8080/api/mypage/insert
Content-Type: application/json
Accept: */*
Access-Control-Allow-Origin: *
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxMTExIiwiYXV0aCI6WyJST0xFX0FETUlOIiwiUk9MRV9VU0VSIl0sImV4cCI6MTY5MzkxNzg3M30.o0M6V2SrwAYA2SP2tGrPqVqS9eVBROIloaRGN7ZiY-GE7UUxTrR2oNu5LmqzDq-HTYDc-H0GrbVpCBFpP0PISQ

{
  "code": "1",
  "orName": "원본",
  "chName": "체인지네임",
  "date": "2023-08-22"
}

###회원 아이디로 연차조회
GET http://localhost:8080/api/mypage/anselect/10003
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIzMzMzIiwiYXV0aCI6WyJST0xFX1VTRVIiXSwiZXhwIjoxNjk0NjYzMjM0fQ.vv3fkdkm07pvHm-MBlNkLlCjnBN59rNTycXm2N6mFTZ2GhjB6UbKKcmHiNqrUdjIVrEIS7AWQ53FMgK8xtfStA
Content-Type: application/json


### 회원아이디로 근태조회
GET http://highcare.coffit.today:8080/api/mypage/manselect/10003?offset=2
Accept: */*
#Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxMTExIiwiYXV0aCI6WyJST0xFX0FETUlOIiwiUk9MRV9VU0VSIl0sImV4cCI6MTY5MzkxNzg3M30.o0M6V2SrwAYA2SP2tGrPqVqS9eVBROIloaRGN7ZiY-GE7UUxTrR2oNu5LmqzDq-HTYDc-H0GrbVpCBFpP0PISQ
#Content-Type: application/json
