### 사원 전체 조회
GET http://localhost:8080/api/pm/all?offset=1
Content-Type: application/json
Accept: */*


### 사원 단건 조회
GET http://localhost:8080/api/pm/search
Content-Type: application/json
Accept: */*

{
  "empName": "전아림"
}

### 사원 등록
POST http://localhost:8080/api/pm/all
Content-Type: application/json; boundary=WebAppBoundary
Accept: */*

{
  "empName" : "사계절",
  "empEmail" : "aa@masda.com",
  "phone" : "010-1321-4564",
  "residentNo" : "1321546-5464578",
  "startDate" : "2023-08-22",
  "endDate" : null,
  "isResignation" : "N",
  "deptCode" : 1,
  "jobCode" : 2,
  "address" : "서울시",
  "education" : "종로대학교",
  "telephone" : "013-2441-6454"
}


### 부서조회/
Content-Type: application/json
Accept: */*

### 사원 부서 조회
GET http://localhost:8080/api/pm/empde
Content-Type: application/json
Accept: */*

### 부서조회
GET http://localhost:8080/api/pm/selectDept
Content-Type: application/json
Accept: */*
Access-Control-Allow-Origin: *

### 간단 트리뷰
GET http://localhost:8080/api/pm/secondDept
Content-Type: application/json
Accept: */*
Access-Control-Allow-Origin: *




